"team_name": "Chatbots-R-Us" # Your team name
"eval_method": ["mcqa", "quantiz"] # mcqa, reward, rag, compression
"task_type": "seq2seq" # causal_lm, seq2seq
"policy_model_path": "celinekalb/chatbots-r-us-flan-t5-large-sft-dpo-mcqa" # Your path to the final checkpoint
"reference_model_path": "google/flan-t5-large" # The repo id of your pretrained reference model
"quantized_policy_model_path": "celinekalb/chatbots-r-us-flan-t5-large-sft-dpo-mcqa-quantization-opt" # Your path to the final quantized checkpoint
"rag_policy_model_path": "" # Your path to the final RAG checkpoint
"test_data_path": "./datasets/mcqa/test/mcqa_mmlu_test.jsonl" # Your path to the test data
"dpo_model_args": {} # Put any model arguments required to load your DPO model below
"rag_model_args": # Put any model arguments required to load your rag model below
  "encoder_model_path": ""
  "retriever_model_path": ""
  "document_dir": ""
"quantized_model_args": {"dpo_training" : False} # Put any model arguments required to load your quantized model below
